const types = {
    LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
    LOAD_DATA_FAILURE: 'LOAD_DATA_FAILURE',
    LOAD_DATA_REQUEST: 'LOAD_DATA_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS'
}

export default types